
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 2014.2
* DO NOT EDIT.
*
* hsm v2014.2
SW Build 928826 on Thu Jun  5 17:59:37 MDT 2014
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsdps.h"

/*
* The configuration table for devices
*/

XSdPs_Config XSdPs_ConfigTable[] =
{
	{
		XPAR_PS7_SD_0_DEVICE_ID,
		XPAR_PS7_SD_0_BASEADDR,
		XPAR_PS7_SD_0_SDIO_CLK_FREQ_HZ
	}
};


