// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Sun Jan 19 11:24:58 2014

fifo fifo_inst
(
	.reset(reset_sig) ,	// input  reset_sig
	.clock(clock_sig) ,	// input  clock_sig
	.ifaddr(ifaddr_sig) ,	// output [1:0]:faddr[1:0]] ifaddr_sig
	.slwr(slwr_sig) ,	// output  slwr_sig
	.pktend(pktend_sig) ,	// output  pktend_sig
	.fd(fd_sig) 	// output [7:0]:d[7:0]] fd_sig
);

defparam fifo_inst.Idle = 0;
defparam fifo_inst.select_fifo = 1;
defparam fifo_inst.is_full = 2;
defparam fifo_inst.drop = 3;
defparam fifo_inst.packet_end = 4;
defparam fifo_inst.more_data = 5;
defparam fifo_inst.write_data = 6;
defparam fifo_inst.setup_data = 7;
