# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {
  C:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0
  C:/Users/me/Projects/Zynq/ip_repo/rxMapleLite_1.0.1
  C:/Users/me/Projects/Zynq/ip_repo/rxMapleBusLite_1.0
  C:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0
} [current_fileset]

read_ip c:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0/src/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files c:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0/src/fifo_generator_0/fifo_generator_0.dcp]
set_property used_in_implementation false [get_files -all c:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0/src/fifo_generator_0/fifo_generator_0.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0/src/fifo_generator_0/fifo_generator_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/me/projects/zynq/ip_repo/edit_rxMapleBus_v1_0.cache/wt [current_project]
set_property parent.project_dir c:/users/me/projects/zynq/ip_repo [current_project]
synth_design -top fifo_generator_0 -part xc7z010clg400-1 -mode out_of_context

rename_ref -prefix_all fifo_generator_0
write_checkpoint -noxdef fifo_generator_0.dcp
report_utilization -file fifo_generator_0_utilization_synth.rpt -pb fifo_generator_0_utilization_synth.pb
if { [catch {
  file copy -force c:/users/me/projects/zynq/ip_repo/edit_rxMapleBus_v1_0.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp c:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0/src/fifo_generator_0/fifo_generator_0.dcp
  write_verilog -force -mode synth_stub c:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0/src/fifo_generator_0/fifo_generator_0_stub.v
  write_vhdl -force -mode synth_stub c:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0/src/fifo_generator_0/fifo_generator_0_stub.vhdl
  write_verilog -force -mode funcsim c:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0/src/fifo_generator_0/fifo_generator_0_funcsim.v
  write_vhdl -force -mode funcsim c:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0/src/fifo_generator_0/fifo_generator_0_funcsim.vhdl
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy supporting IP files."
}
