# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {
  C:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0
  C:/Users/me/Projects/Zynq/ip_repo/rxMapleLite_1.0.1
  C:/Users/me/Projects/Zynq/ip_repo/rxMapleBusLite_1.0
  C:/Users/me/Projects/Zynq/ip_repo/rxMapleBus_1.0
} [current_fileset]
add_files -quiet c:/users/me/projects/zynq/ip_repo/edit_rxMapleBus_v1_0.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp
set_property used_in_implementation false [get_files c:/users/me/projects/zynq/ip_repo/edit_rxMapleBus_v1_0.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp]
read_verilog -library xil_defaultlib {
  c:/users/me/projects/zynq/ip_repo/rxmaplebus_1.0/hdl/rxMapleBus_v1_0_S_AXI_CRTL.v
  c:/users/me/projects/zynq/ip_repo/rxmaplebus_1.0/hdl/rxMapleBus_v1_0.v
}
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/me/projects/zynq/ip_repo/edit_rxMapleBus_v1_0.cache/wt [current_project]
set_property parent.project_dir c:/users/me/projects/zynq/ip_repo [current_project]
synth_design -top rxMapleBus_v1_0 -part xc7z010clg400-1
write_checkpoint rxMapleBus_v1_0.dcp
report_utilization -file rxMapleBus_v1_0_utilization_synth.rpt -pb rxMapleBus_v1_0_utilization_synth.pb
