
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 2014.2
* DO NOT EDIT.
*
* hsm v2014.2
SW Build 928826 on Thu Jun  5 17:59:37 MDT 2014
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxidma.h"

/*
* The configuration table for devices
*/

XAxiDma_Config XAxiDma_ConfigTable[] =
{
	{
		XPAR_AXI_DMA_0_DEVICE_ID,
		XPAR_AXI_DMA_0_BASEADDR,
		XPAR_AXI_DMA_0_SG_INCLUDE_STSCNTRL_STRM,
		XPAR_AXI_DMA_0_INCLUDE_MM2S,
		XPAR_AXI_DMA_0_INCLUDE_MM2S_DRE,
		XPAR_AXI_DMA_0_M_AXI_MM2S_DATA_WIDTH,
		XPAR_AXI_DMA_0_INCLUDE_S2MM,
		XPAR_AXI_DMA_0_INCLUDE_S2MM_DRE,
		XPAR_AXI_DMA_0_M_AXI_S2MM_DATA_WIDTH,
		XPAR_AXI_DMA_0_INCLUDE_SG,
		XPAR_AXI_DMA_0_NUM_MM2S_CHANNELS,
		XPAR_AXI_DMA_0_NUM_S2MM_CHANNELS,
		XPAR_AXI_DMA_0_MM2S_BURST_SIZE,
		XPAR_AXI_DMA_0_S2MM_BURST_SIZE,
		XPAR_AXI_DMA_0_MICRO_DMA
	}
};


