
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 2014.2
* DO NOT EDIT.
*
* hsm v2014.2
SW Build 928826 on Thu Jun  5 17:59:37 MDT 2014
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xttcps.h"

/*
* The configuration table for devices
*/

XTtcPs_Config XTtcPs_ConfigTable[] =
{
	{
		XPAR_PS7_TTC_0_DEVICE_ID,
		XPAR_PS7_TTC_0_BASEADDR,
		XPAR_PS7_TTC_0_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PS7_TTC_1_DEVICE_ID,
		XPAR_PS7_TTC_1_BASEADDR,
		XPAR_PS7_TTC_1_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PS7_TTC_2_DEVICE_ID,
		XPAR_PS7_TTC_2_BASEADDR,
		XPAR_PS7_TTC_2_TTC_CLK_FREQ_HZ
	}
};


